### ISSUE TITLE
ssl_proxy_headers - wrong documentation

### ISSUE THREAD

**Issue by samail** [devopsfaith/krakend-httpsecure#3]
Hi guys, 
Looking a bit into this middleware it seems that "ssl_proxy_headers" as specified in the documentation does not exist. 
Shoudl be replaced by "host_proxy_headers"

**Comment by kpacha** [comment]
the middleware is not using the latest versions of the package `github.com/unrolled/secure`. it uses this one https://github.com/unrolled/secure/tree/0f73fc7feba662a2ad5ff887fe203af08f8f8716 . in that version, the var is named `SSLProxyHeaders`
